services:
  - type: web
    name: cardio-health
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7